### PR TITLE
Pure ESP-IDF and Arduino-independence

### PR DESCRIPTION
**Pull request by nicklasb**
Hi,

First, this is not an actual request to pull this code, way too ugly yet, but rather a question:
I use ESP-IDF and ESP32, and:
1. It was fairly easy to make it work in ESP-IF, just had to make proxies for round(), millis() and delay()
2. I realised that that basically makes it Arduino independent as well, as I then could remove that as well.

Do you think something like this would be interesting to add to the library?
It would make it much easier to use on the ESP32, and much more lightweight, as one would not have do drag along Arduino and handle its behaviour.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
I am making new version, which separates time routines like millis to an other platform dependent module. Before I can publish it, I have to investigate some N2k things. So this would be soon replaced. I'll expect to get new version in 2-3 weeks. So please remove this pull.

**Comment by nicklasb** [comment]
Awesome! Closing.

**Comment by phatpaul** [comment]
I was looking for some documentation or example of how to use this library with plain ESP-IDF (no Arduino).  Can you please point me to any resources or write a steps to point me in the right direction?

**Comment by ttlappalainen** [comment]
You should be able just include  libraries and use them:

#include <NMEA2000_esp32.h>

#define ESP32_CAN_TX_PIN GPIO_NUM_16
#define ESP32_CAN_RX_PIN GPIO_NUM_17
tNMEA2000 &NMEA2000=*(new tNMEA2000_esp32(ESP32_CAN_TX_PIN,ESP32_CAN_RX_PIN));

**Comment by phatpaul** [comment]
FYI to answer my own question, here's how I used it with ESP-IDF: https://github.com/phatpaul/NMEA2000_switchbank_example_esp-idf

**Pull request closed without merging**
