### PR TITLE
enum tN2kGNSStype in N2kTypes.h wrong?

### PR DESCRIPTION
**Pull request by ronzeiller**
Would make me wonder, if NMEA2000 would be so different from EPFD Fix Types used in AIS?

**Sources for AIS:** 
https://gpsd.gitlab.io/gpsd/AIVDM.html#_type_5_static_and_voyage_related_data -> Table 10
https://www.navcen.uscg.gov/?pageName=AISMessagesAStatic#

**Sources NMEA2000:**
Could not find official document, but something at CANBoat:
https://github.com/canboat/canboat/blob/master/analyzer/pgn.h

Some sources say also: 15=Internal GNSS, but this could be for AIS only?

### CODE REVIEW

**Comment by ttlappalainen** [comment]
You looked it wrong. You should read GNS type from row:
#define LOOKUP_GNS ( ",0=GPS,1=GLONASS,2=GPS+GLONASS,3=GPS+SBAS/WAAS,4=GPS+SBAS/WAAS+GLONASS,5=Chayka,6=integrated,7=surveyed,8=Galileo" )

**Comment by ttlappalainen** [comment]
There is own type for AIS:
#define LOOKUP_GNS_AIS ( ",0=undefined,1=GPS,2=GLONASS,3=GPS+GLONASS,4=Loran-C,5=Chayka,6=integrated,7=surveyed,8=Galileo" )

For AIS you have to create tN2kGNSStypeAIS

**Comment by ronzeiller** [comment]
```
ParseN2kPGN129794(const tN2kMsg &N2kMsg, uint8_t &MessageID, tN2kAISRepeat &Repeat, uint32_t &UserID, uint32_t &IMOnumber, char *Callsign, char *Name, uint8_t &VesselType, double &Length, double &Beam, double &PosRefStbd, double &PosRefBow, uint16_t &ETAdate, double &ETAtime, double &Draught, char *Destination, tN2kAISVersion &AISversion, tN2kGNSStype &GNSStype, tN2kAISDTE &DTE, tN2kAISTranceiverInfo &AISinfo)
```

One information sent with PGN 129794 is "Type of Electronic Positioning Device"
Where did you find the definition for this?

E.g.: if **tN2kGNSStype &GNSStype**   returns 0 would it be then 0 for "undefined" or would I get 0 for "GPS"?

**Comment by ttlappalainen** [comment]
Please cancel all your changes to tN2kGNSStype, since the current one is right!

**Comment by ronzeiller** [comment]
Sorry, I am no github guru  ;-)
Thought it would be wise to do a Pull Request to show what I mean....

But the question still is: what is meant when I get back e.g 0 in tN2kGNSStype &GNSStype from ParseN2kPGN129794?

**Comment by ttlappalainen** [comment]
I am neither, but got it working. Use pull requests only when you have fully tested code or clear fix. Make e.g. pull request just for those break fixes. Use issues for questions like this.

As in canboat pgn.h field description has LOOKUP_GNS_AIS not LOOKUP_GNS. Thats why we need create new type tN2kGNSStypeAIS for AIS messages. Just add to N2kTypes .h that new enum type and its value, then you can use it on the 129794 and other AIS messages and you get back tN2kGNSStypeAIS &GNSStype.

This is just one more thing I do not understand on NMEA2000 - why they do have different types.

**Comment by ronzeiller** [comment]
Discussion continuing her: https://github.com/ttlappalainen/NMEA2000/issues/154

**Pull request closed without merging**
