### PR TITLE
Add support for Thruster Network Messages (PGNs 128006, 128007 & 128008)

### PR DESCRIPTION
**Pull request by preeve9534**
Hello again Timo. Hope you are well.

I wonder if you would be interested in merging these changes which respond to https://www.nmea.org/Assets/20190613%20thruster%20amendment%20128006,%20128007,%20128008.pdf.

* add PGN 128006 Thruster Control Status
* add PGN 128007 Thruster Information
* add PGN 128008 Thruster Motor Status
* add tN2kDD471 and the alias tN2kThrusterMotorEvents
* add tN2kDD473 and the alias tN2kDirectionControl
* add tN2kDD474 and the alias tN2kThrusterRetraction
* add tN2kDD475 and the alias tN2kThrusterControlEvents
* add tN2kDD487 and the alias tN2kMotorPowerType

Paul

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Yes, thanks. I have to test those. How good testing you have done?

I noticed that at least your priority setting is wrong - 128006 and 128008 should have priority 2 and 128007 7.

**Comment by preeve9534** [comment]
Hi Timo. Oohps - I forgot to set the priorities - apologies.  Will push an updated version.

I don't have access to a "real" thruster system that implements these - the only live systems I have tracked down are using proprietary PGNs.  However, I have an internal  project that is using some of the features.

BTW, I noticed some mistakes in N2kMessages.* when I was making updates - mainly spelling mistakes on variable names and missing  type casts on one of the temperature PGNs. Would you like me to push corrections?

P

**Comment by ttlappalainen** [comment]
Corrections are OK as far as they do not affect backward compatibility.

**Comment by ttlappalainen** [comment]
I have not yet time to test this. I added those PGNs to NMEA Simulator, so now I could make cross testing. Due to historical reasons Simulator has different method for parsing and building messages, so it makes as small cross test for itself. It uses also different methods than on library so there should be good coverage. Actisense does not seem to support those PGNs so it does not help for cross testing.

**Comment by preeve9534** [comment]
Yes the Actisense issue was my problem too. I have Maretron, but it doesn't
support them either.

P

**Comment by preeve9534** [comment]
I tried hard to find a CAN based thruster system that used the NMEA
protocol, but every boat I could get access to was using a proprietary
system. Will try harder over the next few weeks.

P

**Comment by preeve9534** [comment]
I do. I've taken to the Teensy 3.2 for recent projects.

P

**Comment by ttlappalainen** [comment]
Please Email me directly, I'll send you instructions

**Comment by ttlappalainen** [comment]
This need some fixes. In general all real type values should be defined as double even they could be shown as integer. Then it is easier to handle them specially, when you read values. So e.g.
SetN2kPGN128006(...double SpeedControl...) {
  N2kMsg.Add1byteUDuble((SpeedControl > 100)?100:0),0.5); 

Note also that speed control has coefficient 0.5.

The same with SetN2kPGN128007(... double MotorPowerRating, double MaximumMotorTemperatureRating,...) 
Also MotorCurrent, TotalMotorOperatingTime

In header file you could add aliases:
SetN2kThrusterControlStatus
SetN2kThrusterInformation
SetN2kThrusterMotorStatus

**Comment by preeve9534** [comment]
Thanks Timo I'll go over this .

P

**Pull request closed without merging**
