### PR TITLE
Adding references to the new NMEA2000_teensy in the READMEs

### PR DESCRIPTION
**Pull request by sarfata**
Thanks @ttlappalainen for this amazing NMEA2000 library. It seems to work very well with a Teensy board.

I have it connected to a NMEA2000 network with a Raymarine i70 and an Airmar DST800. Communication works from the devices to the board and from the board to the i70.

I have noticed that there seemed to be a problem in the conversion of doubles (the speed displayed on the i70 seems to be double the speed I set in the code). I am not sure if that is teensy specific or not. Will continue to look into this.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Hi,

Have you noticed that for library you have to use m/s for setting the 
speed. So  if you set 10 to library, it means 10 m/s, but Raymarine may 
show it in knots and 10 m/s is about 20 knots.

If you need to to anything with NMEA2000<->NMEA0183, I have also library 
for NMEA0183 for that, which I have not yet published. I have my own 
NMEA0183->NMEA2000 converter.

Timo

**Comment by sarfata** [comment]
Thanks, I will check the units. Did not think about that last night. I would love to see the NMEA0183 library, conversion from one to the other is what I am working on at the moment.

**Comment by ttlappalainen** [comment]
Hi,

I published my NMEA0183 library and made example NMEA0183ToN2k. This is 
actually part of the code I use in my device on boat.

Please use my direct email timo.lappalainen@kave.fi.

Timo

**Comment by ttlappalainen** [comment]
Due to my inexperience with GitHub, I made these changes manually to my master branch.

**Pull request closed without merging**
