### PR TITLE
Add SetN2kAddress, add Source/Address alias

### PR DESCRIPTION
**Pull request by jpilet**

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Two things:
 Why it is necessary to have own AddressChanged flag for each device? If you are worrying about polling, now you are polling more. With single flag you poll all changes with single command. Changes happens rarely, but polling all the time. If you want to know which device changed its source, you can compare it to your memory.

Why it is necessary to have synonym for Source? Wouldn't better change be to have synonym SourceAddress? I do not mean that my naming was the best choice, but I think N2k is complex enough without extra synonyms on interface naming.


Please just add void tNMEA2000::SetN2kSource(unsigned char _iAddr, int _iDev)

**Comment by jpilet** [comment]
Regarding Source or Address naming, you use both: GetN2kSource, but ReadResetAddressChanged. My concern is about consistency, ideally only one name should exist.
In my opinion, Address is better, since it can be used as a source address (when sending) or as a destination address (when receiving).
Having a synonym is a way to tend towards this consistency without breaking existing code.
The alternative would be to rename AddressChanged to SourceChanged. Please let me know what you prefer:
1. keep the existing inconsistency
2. adding synonyms
3. change to "Address" everywhere
4. change to "Source" everywhere
My personal preferences would be 2 or 3, but you decide. Other options work, too.

AddressChanged flag for each device: I just have a single concern: SetN2kAddress works on a single device. So it makes sense it resets the flag for this device. But if we have a shared flag, should it reset it or not? we can be in a state where one device has its flag set, and calling SetN2kAddress on another device should not reset it. That's why I made the flag per device.
What do you think? Is my concern clear?

**Comment by ttlappalainen** [comment]
Address changes has its name for historical reasons. I thought it to mean either our source or any bus device address change. I had to put tDeviceList to own class to reduce code size, so it has its own flag. 

Generally on NMEA 2000 we talk about source and destination. And when we are working as device, our address is source.

SetN2kSource does not need to reset AddressChanged. You know that you did it. So you can SetN2kSource and if after that ReadResetAddressChanged returns true, there has been some address claiming and you can go through list and check who has changed address. And normally you use SetN2kSource before open. So if AddressChanged will be set false on contructor as it is on current realease, there is no harm to not to reset it on SetN2kSource. I do not see why you should use SetN2kSource after Open.

Also as I said it is much better to just test million times one variable and in very rear times address claiming happens check through addresses than check million times several variables. In my own solutions I just save all addresses in any change again to EEPROM, but EEPROM saver writes only changed bytes.

Currently I prefer 1. and just add void tNMEA2000::SetN2kSource(unsigned char _iAddr, int _iDev); I can ask others about naming.

**Comment by ttlappalainen** [comment]
I forgot to mention that your changes leads to backward incompatibility, since now as default address will be not set and it will be left to default 255 address. So also leave SetMode as it is:
void SetMode(tN2kMode _N2kMode, unsigned long _N2kSource=15);

**Comment by jpilet** [comment]
Right.
Here's a version that should not break compatibility and that introduces minimal changes.
I solved my concern about AddressChanged by simply backing it up and restoring it at each SetN2kSource call.
InitDevices now initializes addresses as the previous SetMode function was doing with the default arg.
Let me know what you think.

**Comment by ttlappalainen** [comment]
Still some things:
- Please use separator line //***************************************************************************** above the functions.

- What is the difference of two versions of SetMode? The first one just set mode, but initialises on InitDevices() sources starting with default value 15. The second one does the same, but does it twice, which is not big thing, when you do it once on startup. In principle SetMode is not meant to be used after open - I should actually prevent it working after Open. And I do not see why you shout do that.

- I did not find use for you backup/restore for AddressChanged. When you just set address, it does not touch for the AddressChanged - at least I did not see, where it would do that. Also that version of source changing function should be prevented after Open. There is IsInitialized() method for testing has system been started.

**Comment by jpilet** [comment]
[x] Separator line added.
[x] Removed the backup of AddressChanged

- Depending on when SetMode(mode) is called, InitDevices() might already have been called. For example by SetProductInformation, or SetN2kSource() (I just added this now). So SetMode(mode) will not modify the sources if they are set already. The other version of SetMode, again for compatibility, will set the sources, but not necessarily to the default (15+), it will honour the arg. Again, it may do it twice if devices have not been initialized before. Or just once if they were.

- forbidding SetN2kSource after Open is one option. The other option would be to treat it as a PGN 0xFED8 (65240) and start claiming the new source address.
In that case, SetN2kSource would look like:
```
    Devices[iDev].N2kSource=NewAddress;
    Devices[iDev].UpdateAddressClaimEndSource();
    if (IsInitialized()) {
      StartAddressClaim(iDev);
    }
    AddressChanged=true;
```
Then HandleCommandedAddress could be simplified by calling SetN2kSource()
What do you think about this solution?

**Comment by ttlappalainen** [comment]
One problem is that I should do a full set of tests for the library due to reason I mentioned on my mail. The new SetMode and the old SetMode does not make difference. Then you can add SetN2kSource(unsigned char _iAddr, int _iDev); , since that does not effect anyhow to existing code, since it will not be used on them. Just define one comment that you have to use SetMode before SetN2kSource.

Could you explain why you would like to change address from your application after Open? I do not see any purpose for it, since the behaviour is almost the same is you source 1 or 251. It is in very rear situations, where it has effects and requires a lot of traffic.

**Comment by atestani** [comment]
I  have serious concerns about these type of changes.  I believe that if there isn't a library problem that **requires** fixing, changes should not be made, especially if the issue could/should be resolved in the application code. Changes to naming conventions (which are never perfect, anyway), address claiming, and/or mode change functions could break the library with respect to backward compatibility (at best) to compliance with NMEA standards and certification requirements.   (Please do not start any meta discussion on NMEA, certification, or any of that stuff!  There are places to do that and this forum isn't one of them).

At this point, the library is working perfectly fine.  The old saying: "if it ain't broke... don't fix it!" clearly applies here.   With all due respect, I recommend that these changes not be accepted.  Further, for any future change to be considered, it must be proposed  with a strong justification as to why it is *mandatory*.

**Comment by ttlappalainen** [comment]
atestani: I agree your concern, but new function SetN2kSource is required for right functionality to restore addresses on the device startup for multidevice system. With current function SetMode library can only restore first device address right. The new SetN2kSource does not affect library functionality, when it is not used as far as we keep SetMode and other parts untouched. That is also why I am asking to modify only necessary parts.

**Comment by jpilet** [comment]
I did not understand what level of stability you guys are expecting from this repo.
It makes a lot of sense that you want to keep a "certified" version as stable as possible.
So here's what I suggest. Having a "stable" branch, that is certified, and which you allow modifications only for bug fixes. The stable branch does not support multi-devices.
Then there is a "development" branch, not certified yet, on which we add some features. And then, if for example we bring the development branch to certification and it passes, we'll tell you which commit it is, and we can mark that commit as certified, or make it the new stable branch head.
To properly support multiple devices, more changes are to be made:
- saving/setting "ConfigurationInformation"
- adding the possibility to start/stop a device individually. Use case example: our device has an internal GPS, which we may want to activate or not. When activating/de-activating it, it would make sense to create/destroy a device on the n2k bus.

To make development and maintenance on the development branch easier, @jonasseglare and I could contribute automated tests that do some of the checks needed for compliance. Do you like this idea?

**Comment by jpilet** [comment]
replaced by #98

**Pull request closed without merging**
