### PR TITLE
Additional PGN support

### PR DESCRIPTION
**Pull request by adwuk**
Added support for rate of turn, heading, water speed, distance log and wind

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Are you sure that in  PGN127251 N2kMsg.Add2ByteUDouble(RateOfTurn,((1e-3/32.0) * 0.0001)); is right? In my old reference RateOfTurn is 4 byte double. Also the factor is very small.

**Comment by adwuk** [comment]
Well caught on the 2 vs 4 bytes!  I have this definition from the canboat software which I was using:

```
# define RES_HIRES_ROTATION ((1e-3/32.0) * 0.0001)

{ "Rate of Turn", 127251, true, 5, 0,
  { { "SID", BYTES(1), 1, false, 0, "" }
  , { "Rate", BYTES(4), RES_HIRES_ROTATION, true, "rad/s", "" }
  , { 0 }
  }
}
```

**Comment by ttlappalainen** [comment]
A good way to test these PGNs is to make simple sender like I have example MessageSender.ino and feed data to the Actisense NMEA Reader. Since Actisense is certified, they should have right definitions available.

**Comment by adwuk** [comment]
That is what I have been doing.  The recorded data that I have is from the boat in the yard, and so rate of turn is always zero (thankfully)!  I have validated everything else.

**Comment by ttlappalainen** [comment]
You do not need to have real data to validate PGN content. Just open MessageSender.ino, add sending functions for new PGNs to that. Change row NMEA2000.EnableForward(false); -> NMEA2000.EnableForward(true); Load code to board and attach NMEA Reader to the board serial port. Then you see everything board sends to the bus. You even do not need to have it connected to the N2k bus, Then you can verify that the value you set to sending command matches to the reading on NMEA Reader.

**Comment by ttlappalainen** [comment]
I develop and validate these PGN:s so that I firs create sending side as I described. Then I create receiving function by connecting two devices together via bus. There is pair MessageSender.ino and DataDisplay2.ino for that purpose. Then only problem is that even NMEA Reader does not show all PGN:s. There should be new version coming - I do not know when.

**Comment by adwuk** [comment]
Have you tried using the canboat software?  It has pretty good PGN support, and I have compiled it both on Mac and Raspberry Pi.  You can send and receive data using the actisense-serial command and decode with the analyzer command.

So using your method, I will write the sending side and then receive it with 'antisense-serial /dev/ttyUSB0 | analyser’.  If is works, I can record it and then send it back while I write the receiving function.

Thanks for the input.  I will use this method from now on!

**Pull request merged**
