### PR TITLE
Feature/fix build outside of Arduino.

### PR DESCRIPTION
**Pull request by sarfata**
This change is required to be able to compile NMEA2000.h outside of the Arduino environment.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
I did not get it? NMEA2000.h does not have any malloc. NMEA200.cpp has those files in include list. Each file should have only those includes, what they needs.

**Comment by sarfata** [comment]
This is the errors I get: 
{code}
g++ -o .pioenvs/test/lib/NMEA2000-library/N2kDeviceList.o -c -std=c++11 -g -O0 --coverage -Wall -Werror -DPLATFORMIO=30401 -DKBOX_TESTS -I/home/thomas/.platformio/platforms/native/builder/lib/ArduinoJson/src -Isrc/common -Isrc/test/arduinomock -Isrc/test/teensyheaders -Isrc -I.piolibdeps/ArduinoJson/src -Ilib/KBoxLogging/src -I.piolibdeps/NMEA2000-library/src .piolibdeps/NMEA2000-library/src/N2kDeviceList.cpp
In file included from .piolibdeps/NMEA2000-library/src/N2kDeviceList.h:28:0,
from .piolibdeps/NMEA2000-library/src/N2kDeviceList.cpp:25:
.piolibdeps/NMEA2000-library/src/NMEA2000.h: In member function ‘void tNMEA2000::tProductInformation::Clear()’:
.piolibdeps/NMEA2000-library/src/NMEA2000.h:119:63: error: ‘memset’ was not declared in this scope
void Clear() { memset(this,0,sizeof(tProductInformation)); }
^
.piolibdeps/NMEA2000-library/src/NMEA2000.h: In member function ‘bool tNMEA2000::tProductInformation::IsSame(const tNMEA2000::tProductInformation&)’:
.piolibdeps/NMEA2000-library/src/NMEA2000.h:120:108: error: ‘memcmp’ was not declared in this scope
bool IsSame(const tProductInformation &Other) { return memcmp(this,&Other,sizeof(tProductInformation))==0; }
^
g++ -o .pioenvs/test/lib/NMEA2000-library/N2kGroupFunction.o -c -std=c++11 -g -O0 --coverage -Wall -Werror -DPLATFORMIO=30401 -DKBOX_TESTS -I/home/thomas/.platformio/platforms/native/builder/lib/ArduinoJson/src -Isrc/common -Isrc/test/arduinomock -Isrc/test/teensyheaders -Isrc -I.piolibdeps/ArduinoJson/src -Ilib/KBoxLogging/src -I.piolibdeps/NMEA2000-library/src .piolibdeps/NMEA2000-library/src/N2kGroupFunction.cpp
.piolibdeps/NMEA2000-library/src/N2kDeviceList.cpp: In destructor ‘virtual tN2kDeviceList::tInternalDevice::~tInternalDevice()’:
.piolibdeps/NMEA2000-library/src/N2kDeviceList.cpp:356:29: error: ‘free’ was not declared in this scope
if ( ConfI!=0 ) free(ConfI);
^
{code}

The second error should be fixed directly in the CPP file. Sorry about this. Let me update the pull-request.

**Comment by sarfata** [comment]
Ok it's better now.

**Comment by ttlappalainen** [comment]
If you do not mind, please move implementations to the .cpp file. 

Also I prefer to update Readme.md, Version to 4.3.3 on library.json and library.properties.

**Comment by sarfata** [comment]
@ttlappalainen should be all good now.

**Comment by ttlappalainen** [comment]
Thanks!

**Pull request merged**
