### PR TITLE
Corrected byte-swap-32

### PR DESCRIPTION
**Pull request by thomasonw**
Masking values for this swap-32 are incorrecct

### CODE REVIEW

**Comment by ttlappalainen** [comment]
You should first update your branch. There are several changes on the library. I made fix for the master branch.

**Comment by thomasonw** [comment]
My app is size constrained, and the current NMEA2000 lib has grown too big : - )   Will need to look at this at sometime, but for now am focused in the J1939 component of this lib, so am standardized on a down-rev version I know works.

**Comment by ttlappalainen** [comment]
It should have not grown too much, if you define not to use some extensions. See NMEA2000_CompilerDefns.h

**Comment by thomasonw** [comment]
I will do more work, but a quick test (download and go), the code size has increased over 10,000 bytes – from the NMEA2000 lib alone.

 

Here are the details:

 

Using my ‘archived’ copy:

Sketch uses 64248 bytes (99%) of program storage space. Maximum is 64512 bytes.

Global variables use 2370 bytes (57%) of dynamic memory, leaving 1726 bytes for local variables. Maximum is 4096 bytes.

 

Using a direct download-n-go of the latest version:

Sketch uses 74714 bytes (115%) of program storage space. Maximum is 64512 bytes.

Global variables use 2307 bytes (56%) of dynamic memory, leaving 1789 bytes for local variables. Maximum is 4096 bytes.

 

Compiled using ATmega64M1

**Comment by ttlappalainen** [comment]
But did you activte those definitions?
#define N2K_NO_ISO_MULTI_PACKET_SUPPORT 1
#define N2K_NO_GROUP_FUNCTION_SUPPORT 1
#define N2K_NO_HEARTBEAT_SUPPORT 1

**Comment by thomasonw** [comment]
No, just a copy-n-go test.

 

Will spend some more time looking things over, as well as catch up on the documentation and other changes you have done.  Been about a year I think!  Would be good to bring up to date.

**Pull request closed without merging**
