### PR TITLE
Add support for PGN 129041 (Aids to Navigation Report)

### PR DESCRIPTION
**Pull request by MattCairns**
I have added support for a missing PGN that I needed parsed on my system.

-  Added PGN 129041 based on data described in [this document.](https://www.navcen.uscg.gov/?pageName=AISMessage21)
-  Added unittest
-  Use a struct to pass data into the set and parse functions.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
- AtoNType is 5 lowest bits. So bits AtoNType, OffPositionIndicator, VirtualAtoNFlag, AssignedModeFlag  are in wrong order.
- Field 17 is AIS Spare 1 bit and must be set to 0. Then there is Field 18 device type=GNSSType 4 bits.  Then field 19 reserved 3 bits, which must be set to 1
- Field 21 is AISTransceiverInformation first 5 bits and then 3 reserved bit, which must be set to 1
- AtoNName is varstr (not fixed) and can be up to 34 characters.

**Comment by MattCairns** [comment]
I have made some changes to the PR based on your feedback from this PR and also the PR for 130323.  I made the following changes:

- [x] Update to C++ struct
- [x] Add constructor to tN2kAISAtoNReportData
	- False is the specified default for RAIM, Accuracy, VirtualAtoNFlag and AssignedModeFlag. OffPositionIndicator was not specified but I assumed it to be false.
- [x] Add set method for setting AtoNName
- [x] Fixed bit ordering of AtoNType, OffPositionIndicator, VirtualAtoNFlag, AssignedModeFlag.
- [x] Set AIS Spare bit to 0. 
- [x] Set reserved bits after GNSSType to 1
- [x] Field 21 is AISTransceiverInformation first 5 bits and then 3 reserved bit, which must be set to 1
- [x]  AtoNName is varstr (not fixed) and can be up to 34 characters.

**Comment by ttlappalainen** [comment]
- N2kMsg.AddByte(0x00 | (N2kData.GNSSType & 0x0F) << 3 | 0x07); is not right should be
`(N2kData.GNSSType & 0x0F) << 1 | 0xe0);`
- Do for tN2kAISAtoNType as I described for tN2kDataMode. Std name will be tN2kDD305

**Comment by MattCairns** [comment]
I have updated this branch:

- Add tN2kDD305
- Fix GNSSType
- Fix unittest

**Comment by ttlappalainen** [comment]
- small typo N2kMsg.AddByte((N2kData.GNSSType & 0x0F) << 1 | 0xe7); ->N2kMsg.AddByte((N2kData.GNSSType & 0x0F) << 1 | 0xe0);
- On reader GNSS type is wrong should be N2kData.GNSSType = (tN2kGNSStype)( (N2kMsg.GetByte(Index) >> 1) & 0x0f );

**Comment by MattCairns** [comment]
I have corrected the mistake in GNSSType and rebased the changes for PGN130323 from master into this branch.

**Pull request merged**
