### PR TITLE
Add support for PGN 130323 (Meteorlogical Station Data)

### PR DESCRIPTION
**Pull request by MattCairns**
I have added support for a missing PGN that I needed parsed on my system.  

- Added PGN 130323 as described in [this document.](http://seasmart.net/pdf/SeaSmart_HTTP_Protocol_RevG_043012.pdf)
- Tested based on data from a Airmar 200WX weather station.
- Added unittest

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Some fixes:
- Default priority for 130323 is 6
- In first byte first 4 bits is mode. 0 means autonomous mode. Either use that as default or 0xf (NA). Other 4 reserved bits must be set to 1. If necessary, it can be added later as parameter to end of parameter list.
- On setter use const char * instead of char *
- WindAngle resolution is 0.0001 ( Could be WindDirection)
- WindReference uses only 3 bits and higher bits are reserved and must be set to 1
- StationID is limited to 15 chars, just mention in description on .h. I have to add some time limitation to AddVarStr
- Station name is limited to 50 chars.
- Remove SID from .h comment. Message does not have that field.

You could also think would it be better to use structure or class for parameter list. With structure (or class) you can have default constructor for setting default values (NA). Then you can provide structure as const reference for setter and reference for parser.

**Comment by MattCairns** [comment]
I have added the following changes:
- Priority set to 6
- Add tN2kAISMode and set reserved bits to 1
- Use only 3 bits for WindReference and set reserved bits to 1
- Use `const char*` on setter strings
- WindAngle renamed to WindDirection
- WindDirection set to resolution of 0.0001
- Updated header doc to reflect that StationID and StationName are 15 and 50 bytes.
- Removed SID from header doc.
- Updated unittest to reflect changes.

In regards to your comment about passing a struct/class in the parameter list - I do agree that this would be a better way to handle the set and parse functions.  I think it would help simplify and remove repitition out of the code and be less prone to error as a end user.  I know this would greatly simplify my application.
I had thought of this when adding the PR but opted not to as I did not want to go against the style of the other set and parse functions.  Im not sure if this is out of the scope of this PR?

**Comment by MattCairns** [comment]
After giving it some thought I have decided to update the PR to use a struct of data that gets passed into the set and parse functions.  The implementation is much cleaner now.

**Comment by ttlappalainen** [comment]
Gettting better...

- change const tN2kMeteorlogicalStationData N2kData to const tN2kMeteorlogicalStationData &N2kData otherwise it will cause copy of whole structure on setter.
- You have mixed wind Mode bits. Mode bits are the lowest bits so it must be ((unsigned char) N2kData.Mode) & 0x0f)  | 0xf0
- Same with WindReference
- Define struct just c++ style `struct tN2kMeteorlogicalStationData {...};`
- Some time ago I tried to find any reason why not to use constructor for struct to make life even easier. The only reason I found was that it does not then work in const definition. This is not here the case, so you could have default constructor for struct:
```
struct tN2kMeteorlogicalStationData {
...
  tN2kMeteorlogicalStationData () : 
       Mode(0), 
       SystemDate(N2kUInt16NA), 
       SystemTime(N2kDoubleNA),... {
    StationID[0]=0;
    StationName[0]=0;
  }
  void SetStationID(const char *ID) { 
    strncpy(StationID,ID,sizeof(StationID); StationID[sizeof(StationID)-1]=0; 
  } 
  void SetStationName(const char *Name) { 
    strncpy(StationName,Name,sizeof(StationName); StationID[sizeof(StationName)-1]=0;
  } 
};

```
With above definition you will have all data right even you just set some fields. Others will be shown on N2k bus as NA.

By using structures there is a bit more overhead compared to functional version due to double copy of data, but using it is much easier.

**Comment by MattCairns** [comment]
I have update the PR to reflect the changes you suggested:
- Pass struct to set function by reference.
- Fix Mode and WindReference bit ordering. 
  - It's was not clear from the NMEA documentation i was referencing that this was the order but I suppose it makes sense to go from lowest bit to highest.
- Define a constructor for tN2kMetorlogicalStationData as well as setter methods for StationID and StationName

I agree that using a struct is much simpler and makes the code much more readable which likely makes it worth the cost of the performance hit.

Thanks.

**Comment by ttlappalainen** [comment]
Sorry to bother again and again... But almost there.
- in ParseN2kPGN130323 you do not need parameters size_t StationIDMaxSize, size_t StationNameMaxSize. In parser you can simply use N2kMsg.GetVarStr(sizeof(N2kData.StationID), (char*)N2kData.StationID, Index); size that is fixed length char array. If it would be pointer, sizeof would not not work right.
- Also add 1 to StationID and StationName lengths. They have been define 15 and 50, but we need extra place for string termination (0)
- For mode you need to do bit more work. First add to NMEA2000StdTypes.h 
```
enum tN2kDD025 {
                  N2kDD025_Autonomous=0,
                  N2kDD025_Differential=1,
                  N2kDD025_Estimated=2,
                  N2kDD025_Simulator=3,
                  N2kDD025_Manual=4,
                  N2kDD025_Error=0xe,
                  N2kDD025_Unavailable=0xf
                };

```
Then add to N2kTypes.h
```
using tN2kDataMode = tN2kDD025;
//                  N2kDD025_Autonomous=0,
//                  N2kDD025_Differential=1,
//                  N2kDD025_Estimated=2,
//                  N2kDD025_Simulator=3,
//                  N2kDD025_Manual=4,
//                  N2kDD025_Error=0xe,
//                  N2kDD025_Unavailable=0xf

```
Then use tN2kDataMode for data mode. Those DDXXX are on NMEA2000 database definitions and I did not had them available, when I originally wrote the library. But new types should use that way of definition.

Put those definitions in place. So the first will be between tN2kDD002 and tN2kDD072 and tN2kDataMode similary where other aliases exists.

And by the way have you verified setter and parser anyhow. One test is at least make two devices one for sending and one for reaceiving to see that you get same data. This proves that they work in similar way. I am not sure does Actisense Reader parse those. I just added them to my NMEA Simulator, but have not yet published it.

**Comment by MattCairns** [comment]
We will get there eventually, its all good!

- I have removed the maxsize variables
- Added 1 to station name and id lengths
- Added tN2kDD025 defintion

In terms of testing, I have verified that the parse functions does indeed parse real world data as I replayed a canbus log file which I recorded on my vessel, it contains PGN 130323.  I can also verify that the set function gets parsed correctly if sent over my canbus and then read again with the parse function on the other end.  I cannot however verify that the PGN 130323 is parsed correctly from the real world data as I have no other device to verify the parse against - the values seem sane though.

**Pull request merged**
