### PR TITLE
Errors in some AIS PGN's 

### PR DESCRIPTION
**Pull request by pk1965**
found formatting errors in the fields "Communication State" and AISTransceiverInformation"  which caused problems with following fields.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Thanks for finding error.
Some notes. 
- In N2kTypes.h there is definition tN2kAISTranceiverInfo. Now you have changed that to tN2kAISTransceiverInformation. This whould cause compatibility problem, since others has user original. Please do not change type definitions.
- You have changed functions SetN2kPGN129802, SetN2kPGN129038 and SetN2kAISClassAPosition parameter list. This also causes that it will not compile on others anymore. If you need to add parameter, you can add it to end and set default value for it or create inline function call with old parameter list. For parser you need to always add inline function so that old parsers works.
- PGN 129802 has one NMEA reserved bit field before AISTransceiverInfo. NMEA reserved fields has to be set to all bits 1. As far as I have understood this is different than AIS spare or AIS reserved, which should be set to 0.

**Comment by pk1965** [comment]
Actually tN2kAISTranceiverInfo and tN2kAISTransceiverInformation are 
both are in the N2kTypes.h (lines 245 and 283) use and just wanted to do 
some clean up

I thought l only changed 
SetN2kAISClassAPosition,SetN2kAISSafetyRelatedBroadcastMsg and 
SetN2kAISClassAPosition because they actually didn't output the correct 
information when viewed in the NMEA Reader and my plottier

ok on the reserved fields..

I've also started writting PGN's 129798, 129801 and 129808

**Comment by ttlappalainen** [comment]
Seems that I have not been carefull with PR 2021-09-21. It has been added on that time. Remove tN2kAISTransceiverInformation  and fix it to use original tN2kAISTranceiverInfo

**Comment by ttlappalainen** [comment]
Are you working with this?

**Comment by pk1965** [comment]
I have been but currently offline doing my real job..  will be back at it in about a week

**Pull request closed without merging**
