### PR TITLE
Change the AddGroupFunctionHandler to add handlers to the front of th…

### PR DESCRIPTION
**Pull request by jensyeager**
Add the default handler first.
This ensures default handler is always at the end of the list and new handlers
are always in front of the default.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Why do you want to change order?

**Comment by jensyeager** [comment]
Ah, because I was adding my groupfunctionhandlers after Open().  This put my handlers at the end of the list after your default handler which meant my handlers were never being called. After I put my pull request in I realized that you intended they  be added before the Open().  I suggest that the change be made to add the handler at the end of the list as before but just before the default handler at the end of the list.  This would not break anything written before and would allow me to add my handlers after the Open().  It would be more robust.  I am happy to rewrite it that way and resubmit.

 

Thanks,

Jens

**Comment by ttlappalainen** [comment]
My mistake. Need to test, where PGN is 0 and put it before that.

**Comment by ttlappalainen** [comment]
You have in water maker PGn handler:
```
N2kMsg.AddByte((WatermakerStatus & 0x3f) << 2 | 
                   (ProductionStartStop & 0x02));
```
According my knowledge WatermakerStatus is first field and then ProductionStartStop. This means that it should be on lowest bytes
`N2kMsg.AddByte( (WatermakerStatus & 0x3f)  |  (ProductionStartStop & 0x02)<<6 );`

It looks like all bit fields has the same problem.

`N2kMsg.Add2ByteDouble(ProductWaterTemperature, 0.01);`
Should be
`N2kMsg.Add2ByteUDouble(ProductWaterTemperature, 0.01);`

I tried to keep all units in SI, but made mistake with flow rate. Currently there is only fuel flow rate used with unit l/h. so I prefer to use that also for water flow. Then you should change:
N2kMsg.Add2ByteDouble(ProductWaterFlow, 1);
to
N2kMsg.Add2ByteDouble(ProductWaterFlow, 0.1);

Please change also comments to match those units and replace comment
Feed Pressure +/- 32,764 Kpa
to
Feed Pressure +/- 32 764 000 Pa, resolution 100 Pa (note it is Pa not pa)

Also remove commas from number 1000 separator on comments.

Just noticed that comments and units does not match on set and parse functions. E.g.
N2kMsg.Add2ByteDouble(ProductWaterFlow, 1);
ProductWaterFlow = N2kMsg.Get2ByteDouble(.01, Index);
The right is 0.1 for litres/hour.

**Comment by ttlappalainen** [comment]
Also change N2kMsg.Priority = 2; to N2kMsg.Priority = 6;
and add to NMEA2000.cpp
bool IsDefaultFastPacketMessage(unsigned long PGN) {
    ...
    case 130074L: // Waypoint list, pri=7, period=NA
    case 130567L: // Watermaker Input Setting and Status, pri=6, period=2500
    return true;
  ...

**Comment by ttlappalainen** [comment]
Have you checked fixes I recommended?

**Comment by jensyeager** [comment]
Yes and a few more as  well.  I am building an Arduino Mega based controller for my Spectra Watermaker.  I have Maretron N2KView and a DSM410.  The DSM410 has a screen to handle the SeaRecovery Proprietary Message and N2kView handles both the SeaRecovery Proprietary as well as the generic message. So I am able to control my watermaker using either screen through my Arduino.  All the fixes you recommended were correct when I finally got to testing the whole setup.  I have a few more fixes as well.  I was just waiting for my final testing before submitting.  I also got a bit side tracked on a few other life things but should be done shortly.

Jens

**Comment by ttlappalainen** [comment]
Have you done final tests and fixes? You could then update pull request.

I also prefer to have spaces in if and {} on NMEA2000.cpp:
```
        if ( pLastGroupFunctionHandler->pNext != 0 && pLastGroupFunctionHandler->pNext->PGN == 0 ) {
            pGroupFunctionHandler->pNext = pLastGroupFunctionHandler->pNext;
        }

```for clarify.

**Comment by deregtd** [comment]
@jensyeager Did you ever get this all to work?  We just got a boat with an aqua matic compact watermaker with a broken remote, and the new remote is 2500$, so I'm thinking about just handling the PGNs myself in my little raspberry pi-based NMEA 2000 appliance.  Hoping you have some source I can copy for the status parsing and command sending for start/stop. :)

**Comment by jensyeager** [comment]
I did get it working in prototype.  The bulk of the work is done.  But we have been in lockdown here in the marina in Langkawi, Malaysia since March so haven’t really had the opportunity to get it all into production.  I built it on an Arduino. The NMEA2000 code seems to be working well.  I have a Maretron N2K View I use to check the functionality of the code and my N2K appliance.  They talk to each other well.

 

I have to take a look to see if I have all my work checked back into github and I still need to finish up my pull request. I will review over the next day or two and put something together for you to see.

 

Jens

**Comment by ttlappalainen** [comment]
You have to rebuild the pull, since I think I implemented the adding order problem. There is also several other changes after this original pull request.

**Pull request closed without merging**
