### PR TITLE
Added support for PGNs 129285 and 130074 and fixed length of 129283

### PR DESCRIPTION
**Pull request by adwuk**

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Some things. 
1. I think N2kMsg.AddByte(0xC0 | (SupplementaryData & 0x03)<<4 | (NavDirection & 0x15)); shoulf be N2kMsg.AddByte(0xf0 | (SupplementaryData & 0x0c)<<4 | (NavDirection & 0x03));

2. In my document for PGN130074 i have only one reserved byte after Database ID.

3. Note that one NMEA2000 message (fast packet) can carry only 223 chars in maximum. So you should calculate the length of message and prevent appending new waypoints, if that will be reached. This also leads to the thing that you should have possibility to set number of waypoints after you have finished. So I prefer to change:
void SetN2kPGN129285(tN2kMsg &N2kMsg, uint8_t Start, uint8_t Database, uint8_t Route,
+                        bool NavDirection, bool SupplementaryData, char* RouteName, int &idxnItems) {
...
idxnItems=N2kMsg.DataLen;
N2kMsg.Add2ByteUInt(0);
...

and then
bool AppendN2kPGN129285(tN2kMsg &N2kMsg, int idxnItems, uint8_t ID, char* Name, double Latitude, double Longitude) {
int TmpIndex=idxnItems;
uint16_t nItems=N2kMsg.Get2ByteUint(TmpIndex);

if (is there room to add this wp, use N2kMsg.DataLen ) {
  Add waypoint
...
   N2kMsg.Set2ByteUInt(nItems++,idxnItems);  // This is new and has to be added.
  return true;
}
return false;
...

**Comment by adwuk** [comment]
1) On careful inspection (using NMEA Reader) it looks like it is
N2kMsg.AddByte(0xC0 | (SupplementaryData & 0x03)<<4 | (NavDirection & 0x0F));

2) The documents that I have say only one byte also (canboat/analyzer/pgn.h), but if I take it out I get alignment problems with the string in NMEA Reader.  Pretty sure that 2 bytes is right.

3) Point accepted about not exceeding the fast packet size.  I will look to add something

4) Good idea!

**Comment by ttlappalainen** [comment]
1) OK, if it gives right result with that. The we should also fix informatio to pgn.h

2) png.h may also have errors as above.

3) Actually also N2kMsg class should have that check. I'll add it.

4) You should also test can you send WP:s in several messages. So in your own code you should be something like:
int idxnWP;
for (int nWP=0; nWP<MyWPs; nWP++) {
  SetN2kPGN129285(N2kMsg,idxnWP...)
  for (; nWP<MyWPs && AppendN2kPGN129285(N2kMsg,...,idxnWP); nWP++);
  NMEA2000.SendMsg(N2kMsg);
}

**Comment by adwuk** [comment]
Re: point (1) - I'm guessing that SupplementaryData is bool and that NavDirection is some kind of lookup.  Do you agree and do you have the lookup values anywhere?

**Comment by ttlappalainen** [comment]
Actually you do not need to carry idxnWP though the calls, since it is in fixed index and you know it. So it can be just set:
bool AppendN2kPGN129285(tN2kMsg &N2kMsg, uint8_t ID, char* Name, double Latitude, double Longitude) {
int idxnItems=2;
uint16_t nItems=N2kMsg.Get2ByteUint(TmpIndex);

Also since ID is 2 byte int, you should define  uint16_t ID. And do the same for other parameters. Otherwise you can not use right N2kUInt16NA value.

**Comment by ttlappalainen** [comment]
I do not have lookups and not sure about SupplementaryData. I have the smae source as you except I use OpenSkipper database, which I have been updating. The only way to solve it is to send messages e.g. with MessageSender and test different values one by one and reading them with NMEA Reader. Or you can also test them with MFD, if you have one.

**Comment by adwuk** [comment]
Let me know if you have any more comments about the new code.  Seems to be working well, and has implemented the good suggestions you have made.  I haven't had a chance to build the lookups yet, but that can be done later.  The conflict is the change in MaxDataLen from 255 to 233 bytes for fast packets.  I have added support for decoding AIS class A and V position reports but will push those changes once we have finished this one.

**Pull request closed without merging**
