### PR TITLE
new library.json for platformio library manager

### PR DESCRIPTION
**Pull request by ronzeiller**

### CODE REVIEW

**Comment by ttlappalainen** [comment]
Please do not rush. I updated it. Where did you got the version? Does it need to me clued to git version?

**Comment by ronzeiller** [comment]
Oh, sorry, was just trying to help. 
So please ignore the PR.

No, I do not think that it glues you to git.
If I understood it right, it is just for the platformio library manager. 
If you make an update, than, someone gets a message in platformio and could update to your new version very easy.

**Comment by ttlappalainen** [comment]
I merged and updated it, so please take the new version of it. 
But the version is now just something. And an other problem is that no other has never updated readme changes. So this is just an other, which I have to keep ap to date.

I did not find clear answer can keywords have spaces or not.

**Comment by ronzeiller** [comment]
You are right, the version thing just makes more work to maintain...

just delete the version. 
Should work fine without it (as seen at many others)

Also keyword section with spaces should be fine.

**Comment by ttlappalainen** [comment]
According doc version helps fixing your code to that, so I prefer to have it. There are 237 commits. So maybe right version would be something like 3.180.237. As read from docs:
3 incompatible changes
180 new features
237 totally

**Comment by ttlappalainen** [comment]
Read the doc more. Lower numbers must reset on higher changes. So maybe version could be 4.3.1

**Pull request merged**
