### PR TITLE
ParseN2kPGN129029: Don't leave output variables unset.

### PR DESCRIPTION
**Pull request by Andrei-Errapart**
Rationale: This way there are less surprises for the caller.

### CODE REVIEW

**Comment by ttlappalainen** [comment]
I do not think this is relevant. If there are reference stations, they will be initialized. If there is 0 reference stations, why values should be initialized?

**Comment by Andrei-Errapart** [comment]
Good point.


In another library, I added a straightforward NMEA0183SetGGA function, which takes the same arguments as ParseN2kPGN129029 and was surprised to see invalid values for the reference stations in the output string.

Would it be appropriate:
1) Initialize the reference station in the calling function.
2) Add a documentation string in N2kMessages.h stating that the reference station will not be initialized if there are not any

?

**Comment by ttlappalainen** [comment]
Sorry I was unclear. I meant to do both initialization and warning that values does not contain real values. With initialization call to NMEA0183SetGGA works, since it checks NA values and should do proper setting.

**Comment by Andrei-Errapart** [comment]
Absolutely no problem with that.

Corrected.

I could have caught this as well; perhaps I was distracted.

**Pull request merged**
